[build]
rustflags = ["--cfg", "curve25519_dalek_backend=\"serial\""]
rustdocflags = [
	"-Dwarnings",
	"-Arustdoc::redundant_explicit_links", # stylistic
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
	"--cfg",
	"-C",
	"curve25519_dalek_backend=\"serial\"",
	"link-arg=-fuse-ld=lld",
]

[env]
# Needed for musl builds so user doesn't have to install musl-tools.
CC_x86_64_unknown_linux_musl = { value = ".cargo/musl-gcc", force = true, relative = true }
CXX_x86_64_unknown_linux_musl = { value = ".cargo/musl-g++", force = true, relative = true }
CARGO_WORKSPACE_ROOT_DIR = { value = "", relative = true }
SQLX_OFFLINE = "true"

[net]
retry = 5
# git-fetch-with-cli = true # commented because there is a risk that a runner can be banned by github
