name: Rustfmt check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quick_check:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    container:
      image: paritytech/ci-unified:bullseye-1.77.0-2024-04-10-v20240408
    steps:
      - uses: actions/checkout@v5

      - name: Cargo fmt
        run: cargo +nightly fmt --all -- --check
